admin_user = User.find_by(role: "admin")

if admin_user.nil?
  puts "No admin user found. Please seed an admin user before creating properties."
else
  Property.create!([
    {
      user_id: admin_user.id,
      address: "123 Test Address",
      city: "Las Vegas",
      state: "NV",
      country: "USA",
      zipcode: "89123",
      name: "My Property",
      description: "",
      price: "100",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "36.1147",
      coordinates_longitude: "-115.1728",
      created_at: "2025-05-13 06:06:18.703800",
      updated_at: "2025-05-13 06:06:18.703800",
    },
    {
      user_id: admin_user.id,
      address: "123 Address",
      city: "Bryce Canyon City",
      state: "UT",
      country: "USA",
      zipcode: "55443",
      name: "My Village",
      description: "",
      price: "300",
      bedrooms: 1,
      baths: 1,
      max_guests: 2,
      cancellation_policy: "Non-refundable after booking.",
      coordinates_latitude: "37.6239",
      coordinates_longitude: "-112.1677",
      created_at: "2025-05-13 06:37:54.879496",
      updated_at: "2025-05-13 06:37:54.879496",
    },
    {
      user_id: admin_user.id,
      address: "123 Test Address",
      city: "Springdale",
      state: "UT",
      country: "USA",
      zipcode: "01234",
      name: "My cabin house",
      description: "",
      price: "250",
      bedrooms: 2,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "37.1882",
      coordinates_longitude: "-113.0012",
      created_at: "2025-05-13 07:04:23.126429",
      updated_at: "2025-05-13 07:04:23.126429",
    },
    {
      user_id: admin_user.id,
      address: "456 Ocean Drive",
      city: "Santa Monica",
      state: "CA",
      country: "USA",
      zipcode: "90401",
      name: "Beachside Retreat",
      description: "A sunny beachside bungalow just steps from the shore.",
      price: "400",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "34.0195",
      coordinates_longitude: "-118.4912",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "789 Mountain Road",
      city: "Aspen",
      state: "CO",
      country: "USA",
      zipcode: "81611",
      name: "Mountain Escape",
      description: "Perfect for skiing trips and cozy winter nights.",
      price: "500",
      bedrooms: 4,
      baths: 3,
      max_guests: 6,
      cancellation_policy: "Non-refundable during ski season.",
      coordinates_latitude: "39.1911",
      coordinates_longitude: "-106.8175",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "321 Forest Lane",
      city: "Bozeman",
      state: "MT",
      country: "USA",
      zipcode: "59715",
      name: "Rustic Cabin",
      description: "Surrounded by forest with plenty of hiking trails.",
      price: "220",
      bedrooms: 2,
      baths: 1,
      max_guests: 3,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "45.6770",
      coordinates_longitude: "-111.0429",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "100 Desert Ridge",
      city: "Sedona",
      state: "AZ",
      country: "USA",
      zipcode: "86336",
      name: "Red Rock Haven",
      description: "Modern home with stunning views of red rock formations.",
      price: "350",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Full refund if canceled 72 hours before check-in.",
      coordinates_latitude: "34.8697",
      coordinates_longitude: "-111.7609",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "88 Lake View",
      city: "Lake Tahoe",
      state: "NV",
      country: "USA",
      zipcode: "89449",
      name: "Lakeside Lodge",
      description: "Scenic cabin by the lake, ideal for summer fun.",
      price: "450",
      bedrooms: 4,
      baths: 3,
      max_guests: 8,
      cancellation_policy: "No refund within 10 days of check-in.",
      coordinates_latitude: "38.9399",
      coordinates_longitude: "-119.9772",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "77 City Street",
      city: "New Orleans",
      state: "LA",
      country: "USA",
      zipcode: "70130",
      name: "Historic French Quarter Home",
      description: "Live in the heart of New Orleans with rich culture.",
      price: "275",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "29.9511",
      coordinates_longitude: "-90.0715",
      created_at: Time.current,
      updated_at: Time.current,
    },
  ])

  puts "Seeded properties with additional fields."
end
