property_bed_info_data = {
  "My Property" => [["Master Bedroom", "King"], ["Guest Room", "Queen"], ["Kids Room", "Twin"]],
  "My Village" => [["Cozy Bedroom", "Queen"]],
  "My cabin house" => [["Loft", "Queen"], ["Guest Room", "Twin"]],
  "Beachside Retreat" => [["Beach Room", "Queen"], ["Ocean View Room", "King"]],
  "Mountain Escape" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Bunk Room", "Twin"]],
  "Rustic Cabin" => [["Master Bedroom", "King"], ["Second Bedroom", "Full"]],
  "Red Rock Haven" => [["Master Bedroom", "King"], ["Guest Room", "Queen"], ["Kids Room", "Twin"]],
  "Lakeside Lodge" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"], ["Loft", "Twin"]],
  "Historic French Quarter Home" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Ocean View Villa" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Guest Room 3", "Full"], ["Kids Room", "Twin"]],
  "Urban Loft" => [["Studio Bedroom", "Queen"]],
  "Texas Ranch House" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Vineyard Estate" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Garden Room", "Full"]],
  "Harbor View Condo" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Alpine Chalet" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Bunk Room", "Twin"]],
  "Smoky Mountain Cabin" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "South Beach Apartment" => [["Bedroom", "Queen"]],
  "Desert Adventure Base" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Twin"]],
  "Fisherman's Wharf Loft" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Historic District Home" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Cliffside Retreat" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Adobe Casita" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Tropical Paradise" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Garden Room", "Full"]],
  "Wine Country Cottage" => [["Bedroom", "Queen"]],
  "Mountain Peak Lodge" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Guest Room 3", "Full"], ["Loft", "Twin"]],
  "Cajun Country Home" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Capitol Hill Apartment" => [["Bedroom", "Queen"]],
  "Riverside Cabin" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Music Row Loft" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Wild West Lodge" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Bunk Room", "Twin"]],
  "Vermont Farmhouse" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Kids Room", "Twin"]],
  "Waikiki Beach Condo" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Antebellum Mansion" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Garden Room", "Full"]],
  "City Park Townhouse" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Seaside Cottage" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Desert Villa" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Casita", "Full"]],
  "University District Apartment" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Michigan Avenue High-Rise" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Beverly Hills Estate" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Guest Room 3", "Queen"], ["Pool House", "Full"], ["Guest Suite", "King"]],
  "Horse Country Farm" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Barn Loft", "Twin"]],
  "French Quarter Studio" => [["Studio Bedroom", "Queen"]],
  "Volcano Retreat" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Garden Room", "Full"]],
  "Artist's Adobe" => [["Master Bedroom", "King"], ["Studio Room", "Queen"]],
  "Blues District Loft" => [["Loft Bedroom", "Queen"]],
  "Alaska Wilderness Lodge" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Cabin Room", "Full"]],
  "Boardwalk Casino View" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Historic Philly Apartment" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Desert Vista Home" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Historic Prescott House" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Tahoe Ski Chalet" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Bunk Room", "Twin"]],
  "Branson Entertainment House" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Cannery Row Loft" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Stockyards Loft" => [["Loft Bedroom", "Queen"]],
  "Downtown Riverfront Condo" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Midtown Atlanta Apartment" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Beach House Escape" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Guest Room 3", "Full"], ["Beach Room", "Twin"]],
  "Masters Golf Home" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Space City Home" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Vegas Strip Penthouse" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"]],
  "Rocky Mountain Cabin" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Loft", "Twin"]],
  "Jazz District Loft" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Alamo Plaza Condo" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Falls View Suite" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Inner Harbor Condo" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Capitol Hill Townhouse" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Crater Lake Lodge" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Cabin Room", "Full"]],
  "University District Home" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Sonoma Wine Estate" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Wine Cottage", "Queen"], ["Guest House", "Full"]],
  "Disney Area Villa" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Kids Room", "Twin"]],
  "Newport Mansion" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Guest Room 3", "Queen"], ["Tower Room", "Full"]],
  "Redwood Forest Cabin" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Steel City Loft" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Indy 500 Home" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Vermont Mountain Lodge" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Mountain View Room", "Full"]],
  "Mission Bay Beach House" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Beach Room", "Full"]],
  "Colonial Williamsburg Home" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Flagstaff Pine Cabin" => [["Master Bedroom", "King"], ["Guest Room", "Queen"]],
  "Russian Hill Apartment" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Gateway Arch Loft" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Gulf Coast Condo" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Downtown Reno Apartment" => [["Bedroom", "Queen"]],
  "West Hollywood Penthouse" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "North End Brownstone" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Derby City Loft" => [["Master Bedroom", "Queen"], ["Guest Room", "Full"]],
  "Capitol City House" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Emerald Coast Villa" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Beach Room", "Full"]],
  "Park City Ski House" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Queen"], ["Guest Room 3", "Full"], ["Ski Lodge Room", "Twin"]],
  "Elvis District House" => [["Master Bedroom", "King"], ["Guest Room 1", "Queen"], ["Guest Room 2", "Full"]],
  "Canyon Rim Lodge" => [["Master Suite", "King"], ["Guest Room 1", "Queen"], ["Canyon View Room", "Full"]],
}

property_bed_info_data.each do |property_name, beds|
  property = Property.find_by(name: property_name)

  if property
    beds.each do |room, bed_type|
      PropertyBedInfo.create!(
        property_id: property.id,
        room: room,
        bed_type: bed_type,
        is_active: true,
        created_at: Time.current,
        updated_at: Time.current,
      )
    end
    puts "Seeded Bed Info for #{property_name}"
  else
    puts "Property not found: #{property_name}"
  end
end
