admin_user = User.find_by(role: "admin")

if admin_user.nil?
  puts "No admin user found. Please seed an admin user before creating properties."
else
  Property.create!([
    {
      user_id: admin_user.id,
      address: "123 Test Address",
      city: "Las Vegas",
      state: "NV",
      country: "USA",
      zipcode: "89123",
      name: "My Property",
      title: "Charming Desert Oasis",
      property_type: "House",
      description: "",
      price: "100",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "36.1147",
      coordinates_longitude: "-115.1728",
      created_at: "2025-05-13 06:06:18.703800",
      updated_at: "2025-05-13 06:06:18.703800",
    },
    {
      user_id: admin_user.id,
      address: "123 Address",
      city: "Bryce Canyon City",
      state: "UT",
      country: "USA",
      zipcode: "55443",
      name: "My Village",
      title: "Cozy Village Retreat",
      property_type: "Cottage",
      description: "",
      price: "300",
      bedrooms: 1,
      baths: 1,
      max_guests: 2,
      cancellation_policy: "Non-refundable after booking.",
      coordinates_latitude: "37.6239",
      coordinates_longitude: "-112.1677",
      created_at: "2025-05-13 06:37:54.879496",
      updated_at: "2025-05-13 06:37:54.879496",
    },
    {
      user_id: admin_user.id,
      address: "123 Test Address",
      city: "Springdale",
      state: "UT",
      country: "USA",
      zipcode: "01234",
      name: "My cabin house",
      title: "Rustic Mountain Cabin",
      property_type: "Cabin",
      description: "",
      price: "250",
      bedrooms: 2,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "37.1882",
      coordinates_longitude: "-113.0012",
      created_at: "2025-05-13 07:04:23.126429",
      updated_at: "2025-05-13 07:04:23.126429",
    },
    {
      user_id: admin_user.id,
      address: "456 Ocean Drive",
      city: "Santa Monica",
      state: "CA",
      country: "USA",
      zipcode: "90401",
      name: "Beachside Retreat",
      title: "Sunny Beachside Bungalow",
      property_type: "Bungalow",
      description: "A sunny beachside bungalow just steps from the shore.",
      price: "400",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "34.0195",
      coordinates_longitude: "-118.4912",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "789 Mountain Road",
      city: "Aspen",
      state: "CO",
      country: "USA",
      zipcode: "81611",
      name: "Mountain Escape",
      title: "Luxury Mountain Resort",
      property_type: "Resort",
      description: "Perfect for skiing trips and cozy winter nights.",
      price: "500",
      bedrooms: 4,
      baths: 3,
      max_guests: 6,
      cancellation_policy: "Non-refundable during ski season.",
      coordinates_latitude: "39.1911",
      coordinates_longitude: "-106.8175",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "321 Forest Lane",
      city: "Bozeman",
      state: "MT",
      country: "USA",
      zipcode: "59715",
      name: "Rustic Cabin",
      title: "Forest Cabin Retreat",
      property_type: "Cabin",
      description: "Surrounded by forest with plenty of hiking trails.",
      price: "220",
      bedrooms: 2,
      baths: 1,
      max_guests: 3,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "45.6770",
      coordinates_longitude: "-111.0429",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "100 Desert Ridge",
      city: "Sedona",
      state: "AZ",
      country: "USA",
      zipcode: "86336",
      name: "Red Rock Haven",
      title: "Modern Desert Getaway",
      property_type: "House",
      description: "Modern home with stunning views of red rock formations.",
      price: "350",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Full refund if canceled 72 hours before check-in.",
      coordinates_latitude: "34.8697",
      coordinates_longitude: "-111.7609",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "88 Lake View",
      city: "Lake Tahoe",
      state: "NV",
      country: "USA",
      zipcode: "89449",
      name: "Lakeside Lodge",
      title: "Scenic Lakeside Cabin",
      property_type: "Cabin",
      description: "Scenic cabin by the lake, ideal for summer fun.",
      price: "450",
      bedrooms: 4,
      baths: 3,
      max_guests: 8,
      cancellation_policy: "No refund within 10 days of check-in.",
      coordinates_latitude: "38.9399",
      coordinates_longitude: "-119.9772",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "77 City Street",
      city: "New Orleans",
      state: "LA",
      country: "USA",
      zipcode: "70130",
      name: "Historic French Quarter Home",
      title: "Charming Historic Home",
      property_type: "House",
      description: "Live in the heart of New Orleans with rich culture.",
      price: "275",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "29.9511",
      coordinates_longitude: "-90.0715",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "55 Coastal Highway",
      city: "Malibu",
      state: "CA",
      country: "USA",
      zipcode: "90265",
      name: "Ocean View Villa",
      title: "Stunning Ocean View Estate",
      property_type: "Villa",
      description: "Luxurious villa with panoramic ocean views.",
      price: "850",
      bedrooms: 5,
      baths: 4,
      max_guests: 10,
      cancellation_policy: "Free cancellation within 72 hours.",
      coordinates_latitude: "34.0259",
      coordinates_longitude: "-118.7798",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "202 Pine Street",
      city: "Portland",
      state: "OR",
      country: "USA",
      zipcode: "97204",
      name: "Urban Loft",
      title: "Modern Downtown Loft",
      property_type: "Apartment",
      description: "Stylish loft in the heart of downtown Portland.",
      price: "180",
      bedrooms: 1,
      baths: 1,
      max_guests: 2,
      cancellation_policy: "Non-refundable after booking.",
      coordinates_latitude: "45.5152",
      coordinates_longitude: "-122.6784",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "303 Ranch Road",
      city: "Austin",
      state: "TX",
      country: "USA",
      zipcode: "78701",
      name: "Texas Ranch House",
      title: "Authentic Texas Ranch",
      property_type: "Ranch",
      description: "Experience true Texas hospitality on this working ranch.",
      price: "320",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "30.2672",
      coordinates_longitude: "-97.7431",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "404 Vineyard Lane",
      city: "Napa",
      state: "CA",
      country: "USA",
      zipcode: "94558",
      name: "Vineyard Estate",
      title: "Elegant Vineyard Retreat",
      property_type: "Estate",
      description: "Beautiful estate surrounded by vineyards.",
      price: "600",
      bedrooms: 4,
      baths: 3,
      max_guests: 8,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "38.2975",
      coordinates_longitude: "-122.2869",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "505 Harbor Drive",
      city: "San Diego",
      state: "CA",
      country: "USA",
      zipcode: "92101",
      name: "Harbor View Condo",
      title: "Waterfront Luxury Condo",
      property_type: "Condo",
      description: "Modern condo with stunning harbor views.",
      price: "375",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "32.7157",
      coordinates_longitude: "-117.1611",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "606 Mountain Pass",
      city: "Jackson Hole",
      state: "WY",
      country: "USA",
      zipcode: "83001",
      name: "Alpine Chalet",
      title: "Cozy Alpine Ski Chalet",
      property_type: "Chalet",
      description: "Perfect ski-in ski-out location with mountain views.",
      price: "550",
      bedrooms: 3,
      baths: 3,
      max_guests: 6,
      cancellation_policy: "Non-refundable during ski season.",
      coordinates_latitude: "43.4799",
      coordinates_longitude: "-110.7624",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "707 River Road",
      city: "Gatlinburg",
      state: "TN",
      country: "USA",
      zipcode: "37738",
      name: "Smoky Mountain Cabin",
      title: "Riverside Mountain Cabin",
      property_type: "Cabin",
      description: "Peaceful cabin along the river in the Smoky Mountains.",
      price: "280",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Full refund if canceled 72 hours before check-in.",
      coordinates_latitude: "35.7143",
      coordinates_longitude: "-83.5102",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "808 Palm Avenue",
      city: "Miami",
      state: "FL",
      country: "USA",
      zipcode: "33139",
      name: "South Beach Apartment",
      title: "Trendy South Beach Studio",
      property_type: "Apartment",
      description: "Steps from the beach and nightlife.",
      price: "225",
      bedrooms: 1,
      baths: 1,
      max_guests: 2,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "25.7907",
      coordinates_longitude: "-80.1300",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "909 Canyon Drive",
      city: "Moab",
      state: "UT",
      country: "USA",
      zipcode: "84532",
      name: "Desert Adventure Base",
      title: "Adventure Seeker's Paradise",
      property_type: "House",
      description: "Perfect base for exploring Arches and Canyonlands.",
      price: "295",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "38.5733",
      coordinates_longitude: "-109.5498",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "1010 Bay Street",
      city: "San Francisco",
      state: "CA",
      country: "USA",
      zipcode: "94133",
      name: "Fisherman's Wharf Loft",
      title: "Historic Wharf Loft",
      property_type: "Loft",
      description: "Iconic location near pier 39 and attractions.",
      price: "420",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "37.8080",
      coordinates_longitude: "-122.4177",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "1111 Garden Way",
      city: "Savannah",
      state: "GA",
      country: "USA",
      zipcode: "31401",
      name: "Historic District Home",
      title: "Charming Southern Mansion",
      property_type: "House",
      description: "Beautiful historic home with garden.",
      price: "340",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "32.0809",
      coordinates_longitude: "-81.0912",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "1212 Cliff Edge",
      city: "Big Sur",
      state: "CA",
      country: "USA",
      zipcode: "93920",
      name: "Cliffside Retreat",
      title: "Dramatic Oceanfront Escape",
      property_type: "House",
      description: "Perched on cliffs with breathtaking views.",
      price: "700",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "No refund within 10 days of check-in.",
      coordinates_latitude: "36.2704",
      coordinates_longitude: "-121.8081",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "1313 Plaza Circle",
      city: "Santa Fe",
      state: "NM",
      country: "USA",
      zipcode: "87501",
      name: "Adobe Casita",
      title: "Traditional Adobe Home",
      property_type: "Casita",
      description: "Authentic southwestern architecture and decor.",
      price: "260",
      bedrooms: 2,
      baths: 1,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "35.6870",
      coordinates_longitude: "-105.9378",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "1414 Island Road",
      city: "Key West",
      state: "FL",
      country: "USA",
      zipcode: "33040",
      name: "Tropical Paradise",
      title: "Island Living at Its Best",
      property_type: "Cottage",
      description: "Tropical oasis with private pool.",
      price: "480",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "24.5551",
      coordinates_longitude: "-81.7800",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "1515 Valley View",
      city: "Napa Valley",
      state: "CA",
      country: "USA",
      zipcode: "94574",
      name: "Wine Country Cottage",
      title: "Romantic Wine Country Escape",
      property_type: "Cottage",
      description: "Intimate cottage among the vines.",
      price: "385",
      bedrooms: 1,
      baths: 1,
      max_guests: 2,
      cancellation_policy: "Free cancellation within 72 hours.",
      coordinates_latitude: "38.5025",
      coordinates_longitude: "-122.4655",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "1616 Summit Peak",
      city: "Telluride",
      state: "CO",
      country: "USA",
      zipcode: "81435",
      name: "Mountain Peak Lodge",
      title: "Luxury Mountain Lodge",
      property_type: "Lodge",
      description: "Ultimate ski resort with spa amenities.",
      price: "950",
      bedrooms: 5,
      baths: 4,
      max_guests: 10,
      cancellation_policy: "Non-refundable during ski season.",
      coordinates_latitude: "37.9375",
      coordinates_longitude: "-107.8123",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "1717 Bayou Lane",
      city: "Lafayette",
      state: "LA",
      country: "USA",
      zipcode: "70506",
      name: "Cajun Country Home",
      title: "Authentic Bayou Experience",
      property_type: "House",
      description: "Experience true Louisiana culture.",
      price: "210",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "30.2241",
      coordinates_longitude: "-92.0198",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "1818 Capitol Hill",
      city: "Seattle",
      state: "WA",
      country: "USA",
      zipcode: "98102",
      name: "Capitol Hill Apartment",
      title: "Hip Urban Apartment",
      property_type: "Apartment",
      description: "Trendy neighborhood with great nightlife.",
      price: "195",
      bedrooms: 1,
      baths: 1,
      max_guests: 2,
      cancellation_policy: "Non-refundable after booking.",
      coordinates_latitude: "47.6205",
      coordinates_longitude: "-122.3212",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "1919 River Bend",
      city: "Bend",
      state: "OR",
      country: "USA",
      zipcode: "97701",
      name: "Riverside Cabin",
      title: "Peaceful River Retreat",
      property_type: "Cabin",
      description: "Serene cabin on the Deschutes River.",
      price: "310",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Full refund if canceled 72 hours before check-in.",
      coordinates_latitude: "44.0582",
      coordinates_longitude: "-121.3153",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "2020 Broadway",
      city: "Nashville",
      state: "TN",
      country: "USA",
      zipcode: "37203",
      name: "Music Row Loft",
      title: "Downtown Nashville Loft",
      property_type: "Loft",
      description: "In the heart of country music capital.",
      price: "265",
      bedrooms: 2,
      baths: 1,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "36.1627",
      coordinates_longitude: "-86.7816",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "2121 Frontier Street",
      city: "Deadwood",
      state: "SD",
      country: "USA",
      zipcode: "57732",
      name: "Wild West Lodge",
      title: "Historic Western Lodge",
      property_type: "Lodge",
      description: "Step back into the Wild West era.",
      price: "240",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "44.3766",
      coordinates_longitude: "-103.7296",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "2222 Maple Drive",
      city: "Burlington",
      state: "VT",
      country: "USA",
      zipcode: "05401",
      name: "Vermont Farmhouse",
      title: "Classic New England Farm",
      property_type: "Farmhouse",
      description: "Charming farmhouse with mountain views.",
      price: "290",
      bedrooms: 4,
      baths: 2,
      max_guests: 7,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "44.4759",
      coordinates_longitude: "-73.2121",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "2323 Coral Way",
      city: "Honolulu",
      state: "HI",
      country: "USA",
      zipcode: "96815",
      name: "Waikiki Beach Condo",
      title: "Beachfront Paradise Condo",
      property_type: "Condo",
      description: "Steps from famous Waikiki Beach.",
      price: "520",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "21.2793",
      coordinates_longitude: "-157.8294",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "2424 Historic Lane",
      city: "Charleston",
      state: "SC",
      country: "USA",
      zipcode: "29401",
      name: "Antebellum Mansion",
      title: "Grand Southern Estate",
      property_type: "Mansion",
      description: "Historic mansion with southern charm.",
      price: "580",
      bedrooms: 4,
      baths: 3,
      max_guests: 8,
      cancellation_policy: "No refund within 10 days of check-in.",
      coordinates_latitude: "32.7765",
      coordinates_longitude: "-79.9311",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "2525 Park Avenue",
      city: "Denver",
      state: "CO",
      country: "USA",
      zipcode: "80205",
      name: "City Park Townhouse",
      title: "Modern Urban Townhouse",
      property_type: "Townhouse",
      description: "Near museums and city attractions.",
      price: "305",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Free cancellation within 72 hours.",
      coordinates_latitude: "39.7392",
      coordinates_longitude: "-104.9903",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "2626 Lighthouse Point",
      city: "Cape Cod",
      state: "MA",
      country: "USA",
      zipcode: "02633",
      name: "Seaside Cottage",
      title: "Quaint New England Cottage",
      property_type: "Cottage",
      description: "Classic Cape Cod beach cottage.",
      price: "365",
      bedrooms: 2,
      baths: 1,
      max_guests: 4,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "41.6688",
      coordinates_longitude: "-70.2962",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "2727 Desert Bloom",
      city: "Scottsdale",
      state: "AZ",
      country: "USA",
      zipcode: "85251",
      name: "Desert Villa",
      title: "Luxurious Desert Oasis",
      property_type: "Villa",
      description: "Resort-style living with pool and spa.",
      price: "625",
      bedrooms: 4,
      baths: 3,
      max_guests: 8,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "33.4942",
      coordinates_longitude: "-111.9261",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "2828 College Avenue",
      city: "Boulder",
      state: "CO",
      country: "USA",
      zipcode: "80302",
      name: "University District Apartment",
      title: "Vibrant College Town Living",
      property_type: "Apartment",
      description: "Walking distance to Pearl Street Mall.",
      price: "215",
      bedrooms: 2,
      baths: 1,
      max_guests: 3,
      cancellation_policy: "Non-refundable after booking.",
      coordinates_latitude: "40.0150",
      coordinates_longitude: "-105.2705",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "2929 Lakefront Drive",
      city: "Chicago",
      state: "IL",
      country: "USA",
      zipcode: "60611",
      name: "Michigan Avenue High-Rise",
      title: "Luxury Lakefront Condo",
      property_type: "Condo",
      description: "Stunning views of Lake Michigan.",
      price: "440",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "41.8781",
      coordinates_longitude: "-87.6298",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "3030 Rodeo Drive",
      city: "Beverly Hills",
      state: "CA",
      country: "USA",
      zipcode: "90210",
      name: "Beverly Hills Estate",
      title: "Glamorous Hollywood Estate",
      property_type: "Estate",
      description: "Live like a celebrity in this luxurious home.",
      price: "1200",
      bedrooms: 6,
      baths: 5,
      max_guests: 12,
      cancellation_policy: "No refund within 10 days of check-in.",
      coordinates_latitude: "34.0736",
      coordinates_longitude: "-118.4004",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "3131 Bluegrass Trail",
      city: "Lexington",
      state: "KY",
      country: "USA",
      zipcode: "40507",
      name: "Horse Country Farm",
      title: "Kentucky Horse Farm",
      property_type: "Farm",
      description: "Experience bluegrass horse country.",
      price: "330",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Full refund if canceled 72 hours before check-in.",
      coordinates_latitude: "38.0406",
      coordinates_longitude: "-84.5037",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "3232 Bourbon Street",
      city: "New Orleans",
      state: "LA",
      country: "USA",
      zipcode: "70116",
      name: "French Quarter Studio",
      title: "Heart of the Quarter",
      property_type: "Studio",
      description: "Right on famous Bourbon Street.",
      price: "245",
      bedrooms: 1,
      baths: 1,
      max_guests: 2,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "29.9584",
      coordinates_longitude: "-90.0644",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "3333 Crater Road",
      city: "Volcano",
      state: "HI",
      country: "USA",
      zipcode: "96785",
      name: "Volcano Retreat",
      title: "Unique Volcanic Experience",
      property_type: "House",
      description: "Near Hawaii Volcanoes National Park.",
      price: "395",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "19.4194",
      coordinates_longitude: "-155.2885",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "3434 Art District",
      city: "Taos",
      state: "NM",
      country: "USA",
      zipcode: "87571",
      name: "Artist's Adobe",
      title: "Creative Adobe Sanctuary",
      property_type: "Adobe",
      description: "Artistic space in historic Taos.",
      price: "255",
      bedrooms: 2,
      baths: 1,
      max_guests: 4,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "36.4072",
      coordinates_longitude: "-105.5731",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "3535 Beale Street",
      city: "Memphis",
      state: "TN",
      country: "USA",
      zipcode: "38103",
      name: "Blues District Loft",
      title: "Memphis Music Scene Loft",
      property_type: "Loft",
      description: "Experience the birthplace of blues.",
      price: "220",
      bedrooms: 1,
      baths: 1,
      max_guests: 2,
      cancellation_policy: "Non-refundable after booking.",
      coordinates_latitude: "35.1495",
      coordinates_longitude: "-90.0490",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "3636 Glacier View",
      city: "Anchorage",
      state: "AK",
      country: "USA",
      zipcode: "99501",
      name: "Alaska Wilderness Lodge",
      title: "Remote Alaskan Adventure",
      property_type: "Lodge",
      description: "Experience true Alaskan wilderness.",
      price: "475",
      bedrooms: 4,
      baths: 2,
      max_guests: 7,
      cancellation_policy: "Free cancellation within 72 hours.",
      coordinates_latitude: "61.2181",
      coordinates_longitude: "-149.9003",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "3737 Casino Boulevard",
      city: "Atlantic City",
      state: "NJ",
      country: "USA",
      zipcode: "08401",
      name: "Boardwalk Casino View",
      title: "Exciting Boardwalk Condo",
      property_type: "Condo",
      description: "Steps from casinos and entertainment.",
      price: "285",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "39.3643",
      coordinates_longitude: "-74.4229",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "3838 Liberty Street",
      city: "Philadelphia",
      state: "PA",
      country: "USA",
      zipcode: "19106",
      name: "Historic Philly Apartment",
      title: "Colonial Era Townhouse",
      property_type: "Townhouse",
      description: "Walk to Independence Hall and Liberty Bell.",
      price: "310",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "39.9526",
      coordinates_longitude: "-75.1652",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "3939 Monument Valley Road",
      city: "Monument Valley",
      state: "UT",
      country: "USA",
      zipcode: "84536",
      name: "Desert Vista Home",
      title: "Iconic Western Landscape",
      property_type: "House",
      description: "Surrounded by famous red rock formations.",
      price: "340",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Full refund if canceled 72 hours before check-in.",
      coordinates_latitude: "36.9980",
      coordinates_longitude: "-110.0985",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "4040 Whiskey Row",
      city: "Prescott",
      state: "AZ",
      country: "USA",
      zipcode: "86301",
      name: "Historic Prescott House",
      title: "Victorian Era Home",
      property_type: "House",
      description: "Charming Victorian in historic downtown.",
      price: "270",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "34.5400",
      coordinates_longitude: "-112.4685",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "4141 Ski Run Boulevard",
      city: "South Lake Tahoe",
      state: "CA",
      country: "USA",
      zipcode: "96150",
      name: "Tahoe Ski Chalet",
      title: "Ultimate Winter Getaway",
      property_type: "Chalet",
      description: "Ski-in ski-out access to Heavenly.",
      price: "675",
      bedrooms: 4,
      baths: 3,
      max_guests: 8,
      cancellation_policy: "Non-refundable during ski season.",
      coordinates_latitude: "38.9399",
      coordinates_longitude: "-119.9772",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "4242 Music Avenue",
      city: "Branson",
      state: "MO",
      country: "USA",
      zipcode: "65616",
      name: "Branson Entertainment House",
      title: "Theater District Home",
      property_type: "House",
      description: "Close to all Branson shows and attractions.",
      price: "235",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "36.6436",
      coordinates_longitude: "-93.2185",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "4343 Lighthouse Avenue",
      city: "Monterey",
      state: "CA",
      country: "USA",
      zipcode: "93940",
      name: "Cannery Row Loft",
      title: "Historic Waterfront Loft",
      property_type: "Loft",
      description: "Steps from famous Cannery Row and aquarium.",
      price: "405",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "36.6002",
      coordinates_longitude: "-121.8947",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "4444 Cattle Drive",
      city: "Fort Worth",
      state: "TX",
      country: "USA",
      zipcode: "76102",
      name: "Stockyards Loft",
      title: "Western Heritage Loft",
      property_type: "Loft",
      description: "In the heart of historic Stockyards.",
      price: "265",
      bedrooms: 1,
      baths: 1,
      max_guests: 2,
      cancellation_policy: "Non-refundable after booking.",
      coordinates_latitude: "32.7555",
      coordinates_longitude: "-97.3308",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "4545 Riverfront Plaza",
      city: "Cincinnati",
      state: "OH",
      country: "USA",
      zipcode: "45202",
      name: "Downtown Riverfront Condo",
      title: "Modern River View Condo",
      property_type: "Condo",
      description: "Overlooking the Ohio River.",
      price: "295",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "39.1031",
      coordinates_longitude: "-84.5120",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "4646 Peachtree Street",
      city: "Atlanta",
      state: "GA",
      country: "USA",
      zipcode: "30309",
      name: "Midtown Atlanta Apartment",
      title: "Hip Midtown Living",
      property_type: "Apartment",
      description: "Walkable to restaurants and culture.",
      price: "250",
      bedrooms: 2,
      baths: 1,
      max_guests: 3,
      cancellation_policy: "Free cancellation within 72 hours.",
      coordinates_latitude: "33.7490",
      coordinates_longitude: "-84.3880",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "4747 Beach Walk",
      city: "Outer Banks",
      state: "NC",
      country: "USA",
      zipcode: "27948",
      name: "Beach House Escape",
      title: "Oceanfront Family Retreat",
      property_type: "House",
      description: "Direct beach access with ocean views.",
      price: "550",
      bedrooms: 5,
      baths: 3,
      max_guests: 10,
      cancellation_policy: "No refund within 10 days of check-in.",
      coordinates_latitude: "35.5585",
      coordinates_longitude: "-75.4665",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "4848 Magnolia Lane",
      city: "Augusta",
      state: "GA",
      country: "USA",
      zipcode: "30901",
      name: "Masters Golf Home",
      title: "Golf Paradise Retreat",
      property_type: "House",
      description: "Near famous Augusta National Golf Club.",
      price: "425",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "33.4735",
      coordinates_longitude: "-82.0105",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "4949 Space Center Drive",
      city: "Houston",
      state: "TX",
      country: "USA",
      zipcode: "77058",
      name: "Space City Home",
      title: "NASA District House",
      property_type: "House",
      description: "Near Johnson Space Center.",
      price: "280",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "29.5586",
      coordinates_longitude: "-95.0903",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "5050 Strip View",
      city: "Las Vegas",
      state: "NV",
      country: "USA",
      zipcode: "89109",
      name: "Vegas Strip Penthouse",
      title: "Luxury Strip Penthouse",
      property_type: "Penthouse",
      description: "Panoramic views of the Las Vegas Strip.",
      price: "750",
      bedrooms: 3,
      baths: 3,
      max_guests: 6,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "36.1147",
      coordinates_longitude: "-115.1728",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "5151 Wilderness Road",
      city: "Estes Park",
      state: "CO",
      country: "USA",
      zipcode: "80517",
      name: "Rocky Mountain Cabin",
      title: "Gateway to Rocky Mountains",
      property_type: "Cabin",
      description: "Perfect base for exploring Rocky Mountain National Park.",
      price: "360",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Full refund if canceled 72 hours before check-in.",
      coordinates_latitude: "40.3772",
      coordinates_longitude: "-105.5217",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "5252 Jazz Street",
      city: "Kansas City",
      state: "MO",
      country: "USA",
      zipcode: "64108",
      name: "Jazz District Loft",
      title: "Historic Jazz District Home",
      property_type: "Loft",
      description: "In the heart of Kansas City jazz scene.",
      price: "230",
      bedrooms: 2,
      baths: 1,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "39.0997",
      coordinates_longitude: "-94.5786",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "5353 Presidio Avenue",
      city: "San Antonio",
      state: "TX",
      country: "USA",
      zipcode: "78205",
      name: "Alamo Plaza Condo",
      title: "Historic Downtown Condo",
      property_type: "Condo",
      description: "Steps from the Alamo and River Walk.",
      price: "275",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Non-refundable after booking.",
      coordinates_latitude: "29.4241",
      coordinates_longitude: "-98.4936",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "5454 Waterfall Way",
      city: "Niagara Falls",
      state: "NY",
      country: "USA",
      zipcode: "14303",
      name: "Falls View Suite",
      title: "Spectacular Falls View",
      property_type: "Suite",
      description: "Watch the falls from your window.",
      price: "410",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "43.0962",
      coordinates_longitude: "-79.0377",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "5555 Marina Boulevard",
      city: "Baltimore",
      state: "MD",
      country: "USA",
      zipcode: "21202",
      name: "Inner Harbor Condo",
      title: "Waterfront Urban Living",
      property_type: "Condo",
      description: "Modern condo at Inner Harbor.",
      price: "320",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "39.2904",
      coordinates_longitude: "-76.6122",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "5656 Capitol Way",
      city: "Washington",
      state: "DC",
      country: "USA",
      zipcode: "20001",
      name: "Capitol Hill Townhouse",
      title: "Historic DC Townhouse",
      property_type: "Townhouse",
      description: "Walk to monuments and museums.",
      price: "465",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "38.9072",
      coordinates_longitude: "-77.0369",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "5757 Crater Lake Road",
      city: "Crater Lake",
      state: "OR",
      country: "USA",
      zipcode: "97604",
      name: "Crater Lake Lodge",
      title: "Mountain Lake Retreat",
      property_type: "Lodge",
      description: "Stunning views of Crater Lake.",
      price: "380",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "No refund within 10 days of check-in.",
      coordinates_latitude: "42.8684",
      coordinates_longitude: "-122.1685",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "5858 College Town Road",
      city: "Ann Arbor",
      state: "MI",
      country: "USA",
      zipcode: "48104",
      name: "University District Home",
      title: "Charming College Town House",
      property_type: "House",
      description: "Near University of Michigan campus.",
      price: "245",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Free cancellation within 72 hours.",
      coordinates_latitude: "42.2808",
      coordinates_longitude: "-83.7430",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "5959 Wine Trail",
      city: "Sonoma",
      state: "CA",
      country: "USA",
      zipcode: "95476",
      name: "Sonoma Wine Estate",
      title: "Premium Wine Country Estate",
      property_type: "Estate",
      description: "Luxury estate among the vineyards.",
      price: "720",
      bedrooms: 5,
      baths: 4,
      max_guests: 10,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "38.2919",
      coordinates_longitude: "-122.4580",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "6060 Theme Park Drive",
      city: "Orlando",
      state: "FL",
      country: "USA",
      zipcode: "32819",
      name: "Disney Area Villa",
      title: "Family Fun Villa",
      property_type: "Villa",
      description: "Minutes from Walt Disney World.",
      price: "395",
      bedrooms: 4,
      baths: 3,
      max_guests: 8,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "28.5383",
      coordinates_longitude: "-81.3792",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "6161 Marina Way",
      city: "Newport",
      state: "RI",
      country: "USA",
      zipcode: "02840",
      name: "Newport Mansion",
      title: "Gilded Age Elegance",
      property_type: "Mansion",
      description: "Historic mansion near famous Newport estates.",
      price: "890",
      bedrooms: 5,
      baths: 4,
      max_guests: 10,
      cancellation_policy: "No refund within 10 days of check-in.",
      coordinates_latitude: "41.4901",
      coordinates_longitude: "-71.3128",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "6262 Redwood Highway",
      city: "Eureka",
      state: "CA",
      country: "USA",
      zipcode: "95501",
      name: "Redwood Forest Cabin",
      title: "Among the Ancient Giants",
      property_type: "Cabin",
      description: "Surrounded by majestic redwood trees.",
      price: "315",
      bedrooms: 2,
      baths: 1,
      max_guests: 4,
      cancellation_policy: "Full refund if canceled 72 hours before check-in.",
      coordinates_latitude: "40.8021",
      coordinates_longitude: "-124.1637",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "6363 Liberty Avenue",
      city: "Pittsburgh",
      state: "PA",
      country: "USA",
      zipcode: "15222",
      name: "Steel City Loft",
      title: "Industrial Chic Loft",
      property_type: "Loft",
      description: "Converted warehouse in cultural district.",
      price: "265",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "40.4406",
      coordinates_longitude: "-79.9959",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "6464 Speedway Boulevard",
      city: "Indianapolis",
      state: "IN",
      country: "USA",
      zipcode: "46222",
      name: "Indy 500 Home",
      title: "Racing Capital House",
      property_type: "House",
      description: "Near the legendary Indianapolis Motor Speedway.",
      price: "290",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "39.7684",
      coordinates_longitude: "-86.1581",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "6565 Foliage Trail",
      city: "Stowe",
      state: "VT",
      country: "USA",
      zipcode: "05672",
      name: "Vermont Mountain Lodge",
      title: "Four Season Mountain Retreat",
      property_type: "Lodge",
      description: "Skiing in winter, foliage in fall.",
      price: "485",
      bedrooms: 4,
      baths: 3,
      max_guests: 8,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "44.4654",
      coordinates_longitude: "-72.6874",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "6666 Mission Bay Drive",
      city: "San Diego",
      state: "CA",
      country: "USA",
      zipcode: "92109",
      name: "Mission Bay Beach House",
      title: "Waterfront Beach Living",
      property_type: "House",
      description: "Private beach access and water sports.",
      price: "560",
      bedrooms: 4,
      baths: 3,
      max_guests: 8,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "32.7767",
      coordinates_longitude: "-117.2491",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "6767 Historic Square",
      city: "Williamsburg",
      state: "VA",
      country: "USA",
      zipcode: "23185",
      name: "Colonial Williamsburg Home",
      title: "Living History Experience",
      property_type: "House",
      description: "Walk to Colonial Williamsburg attractions.",
      price: "335",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Non-refundable after booking.",
      coordinates_latitude: "37.2707",
      coordinates_longitude: "-76.7075",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "6868 Mountain View",
      city: "Flagstaff",
      state: "AZ",
      country: "USA",
      zipcode: "86001",
      name: "Flagstaff Pine Cabin",
      title: "Mountain Town Escape",
      property_type: "Cabin",
      description: "Cool pines and mountain air.",
      price: "295",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Full refund if canceled 72 hours before check-in.",
      coordinates_latitude: "35.1983",
      coordinates_longitude: "-111.6513",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "6969 Trolley Lane",
      city: "San Francisco",
      state: "CA",
      country: "USA",
      zipcode: "94109",
      name: "Russian Hill Apartment",
      title: "Classic San Francisco Living",
      property_type: "Apartment",
      description: "Near cable car lines and Lombard Street.",
      price: "445",
      bedrooms: 2,
      baths: 2,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "37.8024",
      coordinates_longitude: "-122.4200",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "7070 Riverboat Road",
      city: "St. Louis",
      state: "MO",
      country: "USA",
      zipcode: "63102",
      name: "Gateway Arch Loft",
      title: "Downtown Riverfront Loft",
      property_type: "Loft",
      description: "Views of the Gateway Arch.",
      price: "275",
      bedrooms: 2,
      baths: 1,
      max_guests: 3,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "38.6270",
      coordinates_longitude: "-90.1994",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "7171 Beachfront Way",
      city: "Gulf Shores",
      state: "AL",
      country: "USA",
      zipcode: "36542",
      name: "Gulf Coast Condo",
      title: "White Sand Beach Condo",
      property_type: "Condo",
      description: "Direct access to pristine beaches.",
      price: "385",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "30.2460",
      coordinates_longitude: "-87.7008",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "7272 Casino Row",
      city: "Reno",
      state: "NV",
      country: "USA",
      zipcode: "89501",
      name: "Downtown Reno Apartment",
      title: "Biggest Little City Living",
      property_type: "Apartment",
      description: "In the heart of downtown Reno.",
      price: "190",
      bedrooms: 1,
      baths: 1,
      max_guests: 2,
      cancellation_policy: "Non-refundable after booking.",
      coordinates_latitude: "39.5296",
      coordinates_longitude: "-119.8138",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "7373 Sunset Boulevard",
      city: "Los Angeles",
      state: "CA",
      country: "USA",
      zipcode: "90069",
      name: "West Hollywood Penthouse",
      title: "Glamorous WeHo Penthouse",
      property_type: "Penthouse",
      description: "Luxury living on the Sunset Strip.",
      price: "980",
      bedrooms: 3,
      baths: 3,
      max_guests: 6,
      cancellation_policy: "No refund within 10 days of check-in.",
      coordinates_latitude: "34.0901",
      coordinates_longitude: "-118.3712",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "7474 Harbor Point",
      city: "Boston",
      state: "MA",
      country: "USA",
      zipcode: "02109",
      name: "North End Brownstone",
      title: "Historic Boston Living",
      property_type: "Townhouse",
      description: "Charming brownstone in Little Italy.",
      price: "495",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Free cancellation within 72 hours.",
      coordinates_latitude: "42.3601",
      coordinates_longitude: "-71.0589",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "7575 Bourbon Lane",
      city: "Louisville",
      state: "KY",
      country: "USA",
      zipcode: "40202",
      name: "Derby City Loft",
      title: "Kentucky Derby District",
      property_type: "Loft",
      description: "Near Churchill Downs and bourbon trail.",
      price: "255",
      bedrooms: 2,
      baths: 1,
      max_guests: 4,
      cancellation_policy: "Free cancellation within 48 hours.",
      coordinates_latitude: "38.2527",
      coordinates_longitude: "-85.7585",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "7676 Gold Rush Road",
      city: "Sacramento",
      state: "CA",
      country: "USA",
      zipcode: "95814",
      name: "Capitol City House",
      title: "California Capital Living",
      property_type: "House",
      description: "Near state capitol and Old Sacramento.",
      price: "305",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Partial refund up to 7 days before check-in.",
      coordinates_latitude: "38.5816",
      coordinates_longitude: "-121.4944",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "7777 Emerald Coast",
      city: "Destin",
      state: "FL",
      country: "USA",
      zipcode: "32541",
      name: "Emerald Coast Villa",
      title: "Luxury Beach Villa",
      property_type: "Villa",
      description: "Stunning emerald waters and white sand.",
      price: "680",
      bedrooms: 4,
      baths: 4,
      max_guests: 10,
      cancellation_policy: "Free cancellation within 24 hours.",
      coordinates_latitude: "30.3935",
      coordinates_longitude: "-86.4958",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "7878 Mountain Trail",
      city: "Park City",
      state: "UT",
      country: "USA",
      zipcode: "84060",
      name: "Park City Ski House",
      title: "Premier Ski Resort Home",
      property_type: "House",
      description: "Walk to lifts and Main Street.",
      price: "795",
      bedrooms: 5,
      baths: 4,
      max_guests: 10,
      cancellation_policy: "Non-refundable during ski season.",
      coordinates_latitude: "40.6461",
      coordinates_longitude: "-111.4980",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "7979 Graceland Drive",
      city: "Memphis",
      state: "TN",
      country: "USA",
      zipcode: "38116",
      name: "Elvis District House",
      title: "Near Graceland Estate",
      property_type: "House",
      description: "Minutes from Elvis Presley's Graceland.",
      price: "235",
      bedrooms: 3,
      baths: 2,
      max_guests: 5,
      cancellation_policy: "Free cancellation up to 5 days before check-in.",
      coordinates_latitude: "35.0456",
      coordinates_longitude: "-90.0265",
      created_at: Time.current,
      updated_at: Time.current,
    },
    {
      user_id: admin_user.id,
      address: "8080 Grand Canyon Way",
      city: "Grand Canyon Village",
      state: "AZ",
      country: "USA",
      zipcode: "86023",
      name: "Canyon Rim Lodge",
      title: "Grand Canyon Gateway",
      property_type: "Lodge",
      description: "Minutes from South Rim entrance.",
      price: "420",
      bedrooms: 3,
      baths: 2,
      max_guests: 6,
      cancellation_policy: "Full refund if canceled 72 hours before check-in.",
      coordinates_latitude: "36.0544",
      coordinates_longitude: "-112.1401",
      created_at: Time.current,
      updated_at: Time.current,
    }
  ])

  puts "Seeded properties complete"
end
