require "bcrypt"

User.create!([
  {
    username: "jdoe",
    first_name: "John",
    middle_name: "A",
    last_name: "Doe",
    email: "jdoe@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "123-456-7890",
    role: "admin",
  },
  {
    username: "asmith",
    first_name: "Alice",
    middle_name: "",
    last_name: "Smith",
    email: "asmith@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "555-555-5555",
    role: "admin",
  },
  {
    username: "bjones",
    first_name: "Bob",
    middle_name: "C",
    last_name: "Jones",
    email: "bjones@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "987-654-3210",
    role: "admin",
  },
  {
    username: "cwilson",
    first_name: "Carol",
    middle_name: "M",
    last_name: "Wilson",
    email: "cwilson@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "111-222-3333",
    role: "admin",
  },
  {
    username: "emartinez",
    first_name: "Ethan",
    middle_name: "P",
    last_name: "Martinez",
    email: "emartinez@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "444-555-6666",
    role: "admin",
  },
  {
    username: "lthompson",
    first_name: "Laura",
    middle_name: "K",
    last_name: "Thompson",
    email: "lthompson@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "555-666-7777",
    role: "admin",
  },
  {
    username: "mrobinson",
    first_name: "Marcus",
    middle_name: "J",
    last_name: "Robinson",
    email: "mrobinson@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "666-777-8888",
    role: "admin",
  },
  {
    username: "dlee",
    first_name: "David",
    middle_name: "",
    last_name: "Lee",
    email: "dlee@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "222-333-4444",
    role: "user",
  },
  {
    username: "egarcia",
    first_name: "Elena",
    middle_name: "R",
    last_name: "Garcia",
    email: "egarcia@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "333-444-5555",
    role: "user",
  },
  {
    username: "fmiller",
    first_name: "Frank",
    middle_name: "J",
    last_name: "Miller",
    email: "fmiller@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "444-555-6666",
    role: "user",
  },
  {
    username: "gbrown",
    first_name: "Grace",
    middle_name: "",
    last_name: "Brown",
    email: "gbrown@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "555-666-7777",
    role: "user",
  },
  {
    username: "htaylor",
    first_name: "Henry",
    middle_name: "K",
    last_name: "Taylor",
    email: "htaylor@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "666-777-8888",
    role: "user",
  },
  {
    username: "ianderson",
    first_name: "Isabella",
    middle_name: "L",
    last_name: "Anderson",
    email: "ianderson@example.com",
    password_digest: BCrypt::Password.create("password"),
    phone_number: "777-888-9999",
    role: "user",
  },
])
puts "Seeded Users"
