import {
  FaWifi,
  FaTv,
  FaKitchenSet,
  FaSnowflake,
  FaFire,
  FaShower,
  FaUtensils,
  FaKey,
  FaCar,
  FaDumbbell,
  FaElevator,
  FaWheelchair,
  FaPaw,
  FaWind,
  FaBed,
  FaCouch,
  FaComputer,
  FaCamera,
  FaWater,
  FaMoon,
  FaBoxOpen,
  FaFireBurner,
  FaBreadSlice,
  FaTableCellsLarge,
  FaGamepad,
  FaBookOpen,
  FaTree,
  FaChair,
  FaSuitcaseRolling,
  FaCalendarDays,
  FaLock,
} from "react-icons/fa6";
import {
  FaSwimmingPool,
  FaFirstAid,
  FaFireExtinguisher,
  FaSoap,
  FaTshirt as FaShirt,
  FaParking,
} from "react-icons/fa";
import type { IconType } from "react-icons";

export interface AmenityEntry {
  id: string;
  name: string;
  icon: IconType;
}

export const AMENITIES_LIST: AmenityEntry[] = [
  { id: "Wi-Fi", name: "Wi-Fi", icon: FaWifi },
  { id: "TV", name: "TV", icon: FaTv },
  { id: "Air conditioning", name: "Air conditioning", icon: FaSnowflake },
  { id: "Heating", name: "Heating", icon: FaFire },
  { id: "Washer", name: "Washer", icon: FaShirt },
  { id: "Dryer", name: "Dryer", icon: FaWind },
  { id: "Kitchen", name: "Kitchen", icon: FaKitchenSet },
  { id: "Refrigerator", name: "Refrigerator", icon: FaUtensils },
  { id: "Microwave", name: "Microwave", icon: FaKitchenSet },
  { id: "Dishwasher", name: "Dishwasher", icon: FaUtensils },
  { id: "Coffee maker", name: "Coffee maker", icon: FaUtensils },
  { id: "Hot water", name: "Hot water", icon: FaWater },
  { id: "Iron", name: "Iron", icon: FaShirt },
  { id: "Hair dryer", name: "Hair dryer", icon: FaWind },
  { id: "Hangers", name: "Hangers", icon: FaShirt },
  { id: "Bed linens", name: "Bed linens", icon: FaBed },
  { id: "Extra pillows and blankets", name: "Extra pillows and blankets", icon: FaBed },
  { id: "Room-darkening shades", name: "Room-darkening shades", icon: FaMoon },
  { id: "Clothing storage", name: "Clothing storage", icon: FaBoxOpen },
  { id: "Shampoo", name: "Shampoo", icon: FaSoap },
  { id: "Conditioner", name: "Conditioner", icon: FaSoap },
  { id: "Body soap", name: "Body soap", icon: FaSoap },
  { id: "Cooking basics (pots, pans, oil, salt & pepper)", name: "Cooking basics (pots, pans, oil, salt & pepper)", icon: FaKitchenSet },
  { id: "Dishes and silverware", name: "Dishes and silverware", icon: FaUtensils },
  { id: "Stove", name: "Stove", icon: FaFireBurner },
  { id: "Oven", name: "Oven", icon: FaFireBurner },
  { id: "Toaster", name: "Toaster", icon: FaBreadSlice },
  { id: "Dining table", name: "Dining table", icon: FaChair },
  { id: "Toilet paper", name: "Toilet paper", icon: FaShower },
  { id: "Towels", name: "Towels", icon: FaShower },
  { id: "Bathtub", name: "Bathtub", icon: FaShower },
  { id: "Private bathroom", name: "Private bathroom", icon: FaShower },
  { id: "Smart TV", name: "Smart TV", icon: FaTv },
  { id: "Streaming services", name: "Streaming services", icon: FaTv },
  { id: "Board games", name: "Board games", icon: FaGamepad },
  { id: "Books and reading material", name: "Books and reading material", icon: FaBookOpen },
  { id: "Patio or balcony", name: "Patio or balcony", icon: FaCouch },
  { id: "Backyard", name: "Backyard", icon: FaTree },
  { id: "Outdoor dining area", name: "Outdoor dining area", icon: FaChair },
  { id: "BBQ grill", name: "BBQ grill", icon: FaUtensils },
  { id: "Fire pit", name: "Fire pit", icon: FaFire },
  { id: "Free parking on premises", name: "Free parking on premises", icon: FaCar },
  { id: "Paid parking on premises", name: "Paid parking on premises", icon: FaParking },
  { id: "EV charger", name: "EV charger", icon: FaCar },
  { id: "Pool", name: "Pool", icon: FaSwimmingPool },
  { id: "Hot tub", name: "Hot tub", icon: FaSwimmingPool },
  { id: "Gym", name: "Gym", icon: FaDumbbell },
  { id: "Elevator", name: "Elevator", icon: FaElevator },
  { id: "Smoke alarm", name: "Smoke alarm", icon: FaFireExtinguisher },
  { id: "Carbon monoxide alarm", name: "Carbon monoxide alarm", icon: FaFireExtinguisher },
  { id: "First aid kit", name: "First aid kit", icon: FaFirstAid },
  { id: "Fire extinguisher", name: "Fire extinguisher", icon: FaFireExtinguisher },
  { id: "Security cameras on property", name: "Security cameras on property", icon: FaCamera },
  { id: "Dedicated workspace", name: "Dedicated workspace", icon: FaComputer },
  { id: "High-speed Wi-Fi", name: "High-speed Wi-Fi", icon: FaWifi },
  { id: "Wheelchair accessible", name: "Wheelchair accessible", icon: FaWheelchair },
  { id: "Step-free access", name: "Step-free access", icon: FaWheelchair },
  { id: "Accessible parking spot", name: "Accessible parking spot", icon: FaParking },
  { id: "Pets allowed", name: "Pets allowed", icon: FaPaw },
  { id: "Luggage dropoff allowed", name: "Luggage dropoff allowed", icon: FaSuitcaseRolling },
  { id: "Long term stays allowed", name: "Long term stays allowed", icon: FaCalendarDays },
  { id: "Self check-in", name: "Self check-in", icon: FaKey },
  { id: "Keypad", name: "Keypad", icon: FaTableCellsLarge },
  { id: "Lockbox", name: "Lockbox", icon: FaLock },
];

export const amenityIconMap: Record<string, IconType> = Object.fromEntries(
  AMENITIES_LIST.map((amenity) => [amenity.name, amenity.icon])
);
