require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/properties", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Property. As you add validations to Property, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }
  describe "GET /properties" do
    context "when not logged in" do
      it "returns 403 forbidden" do
        get properties_path
        expect(response).to have_http_status(403)
      end
    end
  end

  describe "GET /index" do
    it "renders a successful response" do
      Property.create! valid_attributes
      get properties_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      property = Property.create! valid_attributes
      get property_url(property)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_property_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      property = Property.create! valid_attributes
      get edit_property_url(property)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Property" do
        expect {
          post properties_url, params: { property: valid_attributes }
        }.to change(Property, :count).by(1)
      end

      it "redirects to the created property" do
        post properties_url, params: { property: valid_attributes }
        expect(response).to redirect_to(property_url(Property.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Property" do
        expect {
          post properties_url, params: { property: invalid_attributes }
        }.to change(Property, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post properties_url, params: { property: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested property" do
        property = Property.create! valid_attributes
        patch property_url(property), params: { property: new_attributes }
        property.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the property" do
        property = Property.create! valid_attributes
        patch property_url(property), params: { property: new_attributes }
        property.reload
        expect(response).to redirect_to(property_url(property))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        property = Property.create! valid_attributes
        patch property_url(property), params: { property: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested property" do
      property = Property.create! valid_attributes
      expect {
        delete property_url(property)
      }.to change(Property, :count).by(-1)
    end

    it "redirects to the properties list" do
      property = Property.create! valid_attributes
      delete property_url(property)
      expect(response).to redirect_to(properties_url)
    end
  end

  describe "GET /index with filters" do
    let(:user) { User.create!(email: "test@example.com", password: "password", username: "testuser", first_name: "Test", last_name: "User", role: "user") }
    let!(:property1) {
      Property.create!(
        name: "Beach House", city: "Miami", state: "Florida", country: "USA",
        address: "123 Beach Rd", zipcode: "33101", price: 200, max_guests: 4,
        bedrooms: 2, baths: 2, user: user
      )
    }
    let!(:property2) {
      Property.create!(
        name: "Mountain Cabin", city: "Aspen", state: "Colorado", country: "USA",
        address: "456 Mountain Ave", zipcode: "81611", price: 300, max_guests: 6,
        bedrooms: 3, baths: 2, user: user
      )
    }
    let!(:property3) {
      Property.create!(
        name: "City Apartment", city: "Miami", state: "Florida", country: "USA",
        address: "789 City St", zipcode: "33102", price: 150, max_guests: 2,
        bedrooms: 1, baths: 1, user: user
      )
    }

    it "filters by state" do
      get properties_path, params: { state: "Florida" }
      expect(response).to be_successful
      json_response = JSON.parse(response.body)
      expect(json_response.length).to eq(2)
      expect(json_response.map { |p| p["name"] }).to match_array(["Beach House", "City Apartment"])
    end

    it "filters by city" do
      get properties_path, params: { city: "Miami" }
      expect(response).to be_successful
      json_response = JSON.parse(response.body)
      expect(json_response.length).to eq(2)
      expect(json_response.map { |p| p["name"] }).to match_array(["Beach House", "City Apartment"])
    end

    it "filters by state and city" do
      get properties_path, params: { state: "Florida", city: "Miami" }
      expect(response).to be_successful
      json_response = JSON.parse(response.body)
      expect(json_response.length).to eq(2)
    end

    it "filters by number of guests" do
      get properties_path, params: { guests: 5 }
      expect(response).to be_successful
      json_response = JSON.parse(response.body)
      expect(json_response.length).to eq(1)
      expect(json_response.first["name"]).to eq("Mountain Cabin")
    end

    context "with date filtering" do
      let!(:booking) {
        Booking.create!(
          property: property1,
          user: user,
          start_date: Date.today + 5,
          end_date: Date.today + 10,
          payment_status: "complete"
        )
      }

      it "excludes properties with overlapping bookings" do
        get properties_path, params: {
          checkIn: (Date.today + 6).to_s,
          checkOut: (Date.today + 8).to_s
        }
        expect(response).to be_successful
        json_response = JSON.parse(response.body)
        property_names = json_response.map { |p| p["name"] }
        expect(property_names).not_to include("Beach House")
        expect(property_names).to include("Mountain Cabin", "City Apartment")
      end

      it "includes properties when dates don't overlap" do
        get properties_path, params: {
          checkIn: (Date.today + 15).to_s,
          checkOut: (Date.today + 20).to_s
        }
        expect(response).to be_successful
        json_response = JSON.parse(response.body)
        expect(json_response.length).to eq(3)
      end
    end

    it "combines multiple filters" do
      get properties_path, params: {
        state: "Florida",
        guests: 3
      }
      expect(response).to be_successful
      json_response = JSON.parse(response.body)
      expect(json_response.length).to eq(1)
      expect(json_response.first["name"]).to eq("Beach House")
    end
  end
end
